"""time and data to other table

Revision ID: 132216ed8135
Revises: 65be62580a0b
Create Date: 2024-12-22 18:42:16.847205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132216ed8135'
down_revision: Union[str, None] = '65be62580a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_date')
    op.drop_column('user_book', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_book', sa.Column('date', sa.DATE(), nullable=False))
    op.add_column('transactions', sa.Column('transaction_date', sa.DATE(), nullable=False))
    # ### end Alembic commands ###
