"""add text to Book

Revision ID: 1db24cc7a3f3
Revises: e6fa6b0f6f4e
Create Date: 2024-12-22 23:00:16.566055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db24cc7a3f3'
down_revision: Union[str, None] = 'e6fa6b0f6f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'content')
    # ### end Alembic commands ###
