"""comment fix 2

Revision ID: 812237e9a97f
Revises: b7fb766a63d8
Create Date: 2024-12-22 19:33:41.570705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '812237e9a97f'
down_revision: Union[str, None] = 'b7fb766a63d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments_')
    op.add_column('comments', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('book_id', sa.Integer(), nullable=False))
    op.drop_index('name', table_name='comments')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'books', ['book_id'], ['id'])
    op.drop_column('comments', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('name', mysql.VARCHAR(length=225), nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_index('name', 'comments', ['name'], unique=True)
    op.drop_column('comments', 'book_id')
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'created_at')
    op.drop_column('comments', 'content')
    op.create_table('comments_',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='comments__ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comments__ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
