"""add genre

Revision ID: ee799c5aab9b
Revises: f0c1c0969792
Create Date: 2024-12-22 10:26:38.662296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee799c5aab9b'
down_revision: Union[str, None] = 'f0c1c0969792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', mysql.VARCHAR(length=225), nullable=True))
    # ### end Alembic commands ###
